// Personal details
const PERSONAL_FULL_NAME = 'PERSONAL_FULL_NAME';
const PERSONAL_PHONE = 'PERSONAL_PHONE';
const PERSONAL_EMAIL = 'PERSONAL_EMAIL';
const PERSONAL_LOCATION = 'PERSONAL_LOCATION';
const PERSONAL_LINKEDIN = 'PERSONAL_LINKEDIN';
const PERSONAL_WEBSITE = 'PERSONAL_WEBSITE';

// Target role
const TARGET_ROLE = 'TARGET_ROLE';

// Summary
const SUMMARY_MODE = 'SUMMARY_MODE';
const SUMMARY_MANUAL = 'SUMMARY_MANUAL';
const SUMMARY_BG = 'SUMMARY_BG';
const SUMMARY_STRENGTHS = 'SUMMARY_STRENGTHS';
const SUMMARY_GOAL = 'SUMMARY_GOAL';
const SUMMARY_HIGHLIGHT = 'SUMMARY_HIGHLIGHT';

// Education
const EDUCATION_INTRO = 'EDUCATION_INTRO';
const EDUCATION_SCHOOL = 'EDUCATION_SCHOOL';
const EDUCATION_DEGREE = 'EDUCATION_DEGREE';
const EDUCATION_FIELD = 'EDUCATION_FIELD';
const EDUCATION_LOCATION = 'EDUCATION_LOCATION';
const EDUCATION_START_YEAR = 'EDUCATION_START_YEAR';
const EDUCATION_END_YEAR = 'EDUCATION_END_YEAR';
const EDUCATION_GPA = 'EDUCATION_GPA';
const EDUCATION_COMPLETE = 'EDUCATION_COMPLETE';

// Experience
const EXPERIENCE_INTRO = 'EXPERIENCE_INTRO';
const EXPERIENCE_TITLE = 'EXPERIENCE_TITLE';
const EXPERIENCE_COMPANY = 'EXPERIENCE_COMPANY';
const EXPERIENCE_LOCATION = 'EXPERIENCE_LOCATION';
const EXPERIENCE_START_DATE = 'EXPERIENCE_START_DATE';
const EXPERIENCE_END_DATE = 'EXPERIENCE_END_DATE';
const EXPERIENCE_BULLET = 'EXPERIENCE_BULLET';
const EXPERIENCE_BULLET_ACTION = 'EXPERIENCE_BULLET_ACTION';
const EXPERIENCE_COMPLETE = 'EXPERIENCE_COMPLETE';

// Skills
const SKILLS_INTRO = 'SKILLS_INTRO';
const SKILLS_TECHNICAL = 'SKILLS_TECHNICAL';
const SKILLS_LANGUAGES = 'SKILLS_LANGUAGES';
const SKILLS_OTHER = 'SKILLS_OTHER';

// Phase 3 - Projects
const PROJECTS_INTRO = 'PROJECTS_INTRO';
const PROJECTS_NAME = 'PROJECTS_NAME';
const PROJECTS_ROLE = 'PROJECTS_ROLE';
const PROJECTS_TECH = 'PROJECTS_TECH';
const PROJECTS_DESCRIPTION = 'PROJECTS_DESCRIPTION';
const PROJECTS_COMPLETE = 'PROJECTS_COMPLETE';

// Phase 3 - Activities
const ACTIVITIES_INTRO = 'ACTIVITIES_INTRO';
const ACTIVITIES_TITLE = 'ACTIVITIES_TITLE';
const ACTIVITIES_ORGANIZATION = 'ACTIVITIES_ORGANIZATION';
const ACTIVITIES_DESCRIPTION = 'ACTIVITIES_DESCRIPTION';
const ACTIVITIES_COMPLETE = 'ACTIVITIES_COMPLETE';

// Phase 3 - Certifications
const CERTIFICATIONS_INTRO = 'CERTIFICATIONS_INTRO';
const CERTIFICATIONS_NAME = 'CERTIFICATIONS_NAME';
const CERTIFICATIONS_ISSUER = 'CERTIFICATIONS_ISSUER';
const CERTIFICATIONS_YEAR = 'CERTIFICATIONS_YEAR';
const CERTIFICATIONS_COMPLETE = 'CERTIFICATIONS_COMPLETE';

// Phase 3 - References & Preview
const REFERENCES_INTRO = 'REFERENCES_INTRO';
const PREVIEW = 'PREVIEW';

// Phase 4 - Edit Flow
const EDIT_MENU = 'EDIT_MENU';
const EDIT_PERSONAL = 'EDIT_PERSONAL';
const EDIT_SUMMARY = 'EDIT_SUMMARY';
const EDIT_EDUCATION = 'EDIT_EDUCATION';
const EDIT_EXPERIENCE = 'EDIT_EXPERIENCE';
const EDIT_SKILLS = 'EDIT_SKILLS';
const EDIT_PROJECTS = 'EDIT_PROJECTS';
const EDIT_ACTIVITIES = 'EDIT_ACTIVITIES';
const EDIT_CERTIFICATIONS = 'EDIT_CERTIFICATIONS';
const EDIT_REFERENCES = 'EDIT_REFERENCES';
const EDIT_FINISH = 'EDIT_FINISH';

// Completion
const COMPLETED = 'COMPLETED';

module.exports = {
  PERSONAL_FULL_NAME,
  PERSONAL_PHONE,
  PERSONAL_EMAIL,
  PERSONAL_LOCATION,
  PERSONAL_LINKEDIN,
  PERSONAL_WEBSITE,
  TARGET_ROLE,
  SUMMARY_MODE,
  SUMMARY_MANUAL,
  SUMMARY_BG,
  SUMMARY_STRENGTHS,
  SUMMARY_GOAL,
  SUMMARY_HIGHLIGHT,
  EDUCATION_INTRO,
  EDUCATION_SCHOOL,
  EDUCATION_DEGREE,
  EDUCATION_FIELD,
  EDUCATION_LOCATION,
  EDUCATION_START_YEAR,
  EDUCATION_END_YEAR,
  EDUCATION_GPA,
  EDUCATION_COMPLETE,
  EXPERIENCE_INTRO,
  EXPERIENCE_TITLE,
  EXPERIENCE_COMPANY,
  EXPERIENCE_LOCATION,
  EXPERIENCE_START_DATE,
  EXPERIENCE_END_DATE,
  EXPERIENCE_BULLET,
  EXPERIENCE_BULLET_ACTION,
  EXPERIENCE_COMPLETE,
  SKILLS_INTRO,
  SKILLS_TECHNICAL,
  SKILLS_LANGUAGES,
  SKILLS_OTHER,
  PROJECTS_INTRO,
  PROJECTS_NAME,
  PROJECTS_ROLE,
  PROJECTS_TECH,
  PROJECTS_DESCRIPTION,
  PROJECTS_COMPLETE,
  ACTIVITIES_INTRO,
  ACTIVITIES_TITLE,
  ACTIVITIES_ORGANIZATION,
  ACTIVITIES_DESCRIPTION,
  ACTIVITIES_COMPLETE,
  CERTIFICATIONS_INTRO,
  CERTIFICATIONS_NAME,
  CERTIFICATIONS_ISSUER,
  CERTIFICATIONS_YEAR,
  CERTIFICATIONS_COMPLETE,
  REFERENCES_INTRO,
  PREVIEW,
  EDIT_MENU,
  EDIT_PERSONAL,
  EDIT_SUMMARY,
  EDIT_EDUCATION,
  EDIT_EXPERIENCE,
  EDIT_SKILLS,
  EDIT_PROJECTS,
  EDIT_ACTIVITIES,
  EDIT_CERTIFICATIONS,
  EDIT_REFERENCES,
  EDIT_FINISH,
  COMPLETED,
};